on:
  push:
    branches:
      - main

permissions:
  pages: write

jobs:
  build:
    name: Build Unity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
      - uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: Build-WebGL
          path: build/WebGL/WebGL
      - uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: Build-WebGL
