on:
  push:
    branches:    
      - main

jobs:
  build:
    name: Build Unity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Unity - Builder
        uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Buildd
          path: build
 
