on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Unity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      - uses: game-ci/unity-builder@v4.2.3
        with:
          targetPlatform: WebGL
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: Build-WebGL
          path: build/WebGL/WebGL
      - uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: Build-WebGL
